services:
  - type: web
    name: perfusion-logbook
    env: python-3.10.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
